# RANDOM WALLETS MODE
RANDOM_WALLET = True  # True/False

SLEEP_FROM = 500  # Second
SLEEP_TO = 1000  # Second

QUANTITY_THREADS = 1

THREAD_SLEEP_FROM = 5
THREAD_SLEEP_TO = 5

MAX_PRIORITY_FEE = {
    'opbnb': 0.00001,
}

# RETRY MODE
RETRY_COUNT = 3